[package]
name = "raven-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
ravendb-client = {path = "../ravendb-rs"}
tokio = { version = "1.19.2", features = ["full"] }
